---
apiVersion: v1
kind: Pod
metadata:
  name: splunkchain-pod-DEPLOY_ID
  labels:
    app: splunkchain
    deploy_id: "DEPLOY_ID"
spec:
  containers:
    - name: splunkchain
      image: repo.splunk.com/jan/splunkchain:latest
      env:
        - name: NODE_NAME
          value: "DEPLOY_ID"
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: SPLUNK_START_ARGS
          value: --accept-license
        - name: SPLUNK_PASSWORD
          value: Chang3d!
      ports:
        - name: splunk-port
          containerPort: 8000
        - name: server-port
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: splunkchain-svc-DEPLOY_ID
spec:
  type: NodePort
  selector:
    app: splunkchain
    deploy_id: "DEPLOY_ID"
  ports:
  - protocol: TCP
    name: service-port
    port: 80
    targetPort: 8080
  - protocol: TCP
    name: splunk-port
    port: 8000
    targetPort: 8000
